### ISSUE TITLE
标签莫名其妙有个黑色背景

### ISSUE THREAD

**Issue by nanchen2251** [xiaozhiguang/TagTextView#3]
如题，我的标签是采用的自定义 View，其实只是实现了圆角的 Button，但现在总是有黑色矩形背景，设置 Button 的背景也无效。在其他点使用 该自定义 View 均是正常的。

**Comment by xiaozhiguang** [comment]
可以尝试在当前activity开启硬件加速试试。

**Comment by nanchen2251** [comment]
没有用

**Comment by nanchen2251** [comment]
经检测，不是硬件加速的问题。不过已经解决。多谢。
